sanitize_tables:
  # List of tables and their columns you want sanitized.
  user:
  - mail
trim_tables:
# List of tables to be trimmed (every 4th row kept)
excluded_tables:
# Tables to NOT dump
scrub_tables:
# Tables to dump sans content.
