name: database-janitor-test
recipe: custom
config:
  webroot: .

services:
  real_database:
    type: mariadb
    portforward: 8787
    creds:
      user: real
      password: real
      database: real

  trim_database:
    type: mariadb
    portforward: 8788
    creds:
      user: trim
      password: trim
      database: trim

tooling:
  'db-import ':
    service: :host
    description: Import  into database
    cmd: /helpers/sql-import.sh
    options:
      host:
        description: The database service to use
        default: database
        alias:
        - h
      no-wipe:
        description: Do not destroy the existing database before an import
