name: database-janitor-test
recipe: custom
config:
  webroot: .

services:
  php:
    type: php
    xdebug: true
  database:
    type: mariadb
    portforward: 8787
    creds:
      user: database
      password: database
      database: database

tooling:
  'db-import ':
    service: database
    description: Import into database
    cmd: /helpers/sql-import.sh
